<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="DoctrineTest\InstantiatorTest\Exception\UnexpectedValueExceptionTest" namespace="DoctrineTest\InstantiatorTest\Exception" name="UnexpectedValueExceptionTest" abstract="false" final="false" start="34" end="69">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/doctrine/instantiator/tests/DoctrineTest/InstantiatorTest/Exception" file="UnexpectedValueExceptionTest.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/doctrine/instantiator/tests/DoctrineTest/InstantiatorTest/Exception/UnexpectedValueExceptionTest.php" size="3016" time="2015-12-17T18:44:09+00:00" unixtime="1450377849" sha1="c269892a33c095bd32becb5c5a39347f9cc939aa" relative="vendor/doctrine/instantiator/tests/DoctrineTest/InstantiatorTest/Exception/UnexpectedValueExceptionTest.php"/>
  <docblock>
    <description compact="Tests for {@see \Doctrine\Instantiator\Exception\UnexpectedValueException}"/>
    <author value="Marco Pivetta &lt;ocramius@gmail.com&gt;"/>
    <covers value="\Doctrine\Instantiator\Exception\UnexpectedValueException"/>
  </docblock>
  <extends full="PHPUnit_Framework_TestCase" namespace="" name="PHPUnit_Framework_TestCase"/>
  <method name="testFromSerializationTriggeredException" start="36" end="49" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testFromUncleanUnSerialization" start="51" end="68" abstract="false" final="false" static="false" visibility="public"/>
</class>
