<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="PHP_CodeCoverage_Exception" namespace="" name="PHP_CodeCoverage_Exception" abstract="false" final="false" start="16" end="18">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/php-code-coverage/src/CodeCoverage" file="Exception.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/php-code-coverage/src/CodeCoverage/Exception.php" size="420" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="3ac1985b42fd892f95a394b69e7e2a0119754811" relative="vendor/phpunit/php-code-coverage/src/CodeCoverage/Exception.php"/>
  <docblock>
    <description compact="Exception class for PHP_CodeCoverage component."/>
    <since value="Class available since Release 1.1.0"/>
  </docblock>
  <extends full="RuntimeException" namespace="" name="RuntimeException"/>
</class>
