<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="PHPUnit_Framework_MockObject_Stub_Exception" namespace="" name="PHPUnit_Framework_MockObject_Stub_Exception" abstract="false" final="false" start="18" end="41">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub" file="Exception.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/Exception.php" size="973" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="a2f60cf702a3b1e5b2ac213cc09d0439f5c78610" relative="vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/Exception.php"/>
  <docblock>
    <description compact="Stubs a method by raising a user-defined exception."/>
    <since value="Class available since Release 1.0.0"/>
  </docblock>
  <implements full="PHPUnit_Framework_MockObject_Stub" namespace="" name="PHPUnit_Framework_MockObject_Stub"/>
  <member name="exception" visibility="protected" line="20"/>
  <constructor name="__construct" start="22" end="25" abstract="false" final="false" static="false" visibility="public">
    <parameter name="exception" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
  </constructor>
  <method name="invoke" start="27" end="30" abstract="false" final="false" static="false" visibility="public">
    <parameter name="invocation" byreference="false" type="object">
      <type full="PHPUnit_Framework_MockObject_Invocation" namespace="" name="PHPUnit_Framework_MockObject_Invocation"/>
    </parameter>
  </method>
  <method name="toString" start="32" end="40" abstract="false" final="false" static="false" visibility="public"/>
</class>
