<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="PHPUnit_Framework_AssertionFailedError" namespace="" name="PHPUnit_Framework_AssertionFailedError" abstract="false" final="false" start="16" end="27">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit/src/Framework" file="AssertionFailedError.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit/src/Framework/AssertionFailedError.php" size="635" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="af1e31ca21c15a94763235036ccb3847325ff98b" relative="vendor/phpunit/phpunit/src/Framework/AssertionFailedError.php"/>
  <docblock>
    <description compact="Thrown when an assertion failed."/>
    <since value="Class available since Release 2.0.0"/>
  </docblock>
  <extends full="PHPUnit_Framework_Exception" namespace="" name="PHPUnit_Framework_Exception"/>
  <implements full="PHPUnit_Framework_SelfDescribing" namespace="" name="PHPUnit_Framework_SelfDescribing"/>
  <method name="toString" start="23" end="26" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Wrapper for getMessage() which is declared as final."/>
      <return type="string"/>
    </docblock>
  </method>
</class>
