<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="spec\PhpSpec\Exception\Example\StopOnFailureExceptionSpec" namespace="spec\PhpSpec\Exception\Example" name="StopOnFailureExceptionSpec" abstract="false" final="false" start="9" end="25">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpspec/phpspec/spec/PhpSpec/Exception/Example" file="StopOnFailureExceptionSpec.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpspec/phpspec/spec/PhpSpec/Exception/Example/StopOnFailureExceptionSpec.php" size="530" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="8cb9f15ac3cafe6f7efec802c5fb2d12791c1257" relative="vendor/phpspec/phpspec/spec/PhpSpec/Exception/Example/StopOnFailureExceptionSpec.php"/>
  <extends full="PhpSpec\ObjectBehavior" namespace="PhpSpec" name="ObjectBehavior"/>
  <method name="let" start="11" end="14" abstract="false" final="false" static="false" visibility="public"/>
  <method name="it_is_an_example_exception" start="16" end="19" abstract="false" final="false" static="false" visibility="public"/>
  <method name="it_has_a_the_result_of_the_last_spec" start="21" end="24" abstract="false" final="false" static="false" visibility="public"/>
</class>
