<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\HttpKernel\Tests\DataCollector\ExceptionDataCollectorTest" namespace="Symfony\Component\HttpKernel\Tests\DataCollector" name="ExceptionDataCollectorTest" abstract="false" final="false" start="19" end="39">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-kernel/Tests/DataCollector" file="ExceptionDataCollectorTest.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-kernel/Tests/DataCollector/ExceptionDataCollectorTest.php" size="1235" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="30298a72bbb09da227a4c2495e0761b2d343a759" relative="vendor/symfony/http-kernel/Tests/DataCollector/ExceptionDataCollectorTest.php"/>
  <extends full="PHPUnit_Framework_TestCase" namespace="" name="PHPUnit_Framework_TestCase"/>
  <method name="testCollect" start="21" end="38" abstract="false" final="false" static="false" visibility="public"/>
</class>
