<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Translation\Exception\NotFoundResourceException" namespace="Symfony\Component\Translation\Exception" name="NotFoundResourceException" abstract="false" final="false" start="19" end="21">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/translation/Exception" file="NotFoundResourceException.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/translation/Exception/NotFoundResourceException.php" size="492" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="6d2468f623b8e301ba9a5b81dbfddbed8dd0f945" relative="vendor/symfony/translation/Exception/NotFoundResourceException.php"/>
  <docblock>
    <description compact="Thrown when a resource does not exist."/>
    <author value="Fabien Potencier &lt;fabien@symfony.com&gt;"/>
  </docblock>
  <extends full="InvalidArgumentException" namespace="" name="InvalidArgumentException"/>
  <implements full="Symfony\Component\Translation\Exception\ExceptionInterface" namespace="Symfony\Component\Translation\Exception" name="ExceptionInterface"/>
</class>
