<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\HttpKernel\Tests\HttpKernelTest" namespace="Symfony\Component\HttpKernel\Tests" name="HttpKernelTest" abstract="false" final="false" start="24" end="296">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-kernel/Tests" file="HttpKernelTest.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-kernel/Tests/HttpKernelTest.php" size="11603" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="cd2a8611690704372f85eda102593bf39df8dbe7" relative="vendor/symfony/http-kernel/Tests/HttpKernelTest.php"/>
  <extends full="PHPUnit_Framework_TestCase" namespace="" name="PHPUnit_Framework_TestCase"/>
  <method name="testHandleWhenControllerThrowsAnExceptionAndCatchIsTrue" start="29" end="34" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <expectedexception value="\RuntimeException"/>
    </docblock>
  </method>
  <method name="testHandleWhenControllerThrowsAnExceptionAndCatchIsFalseAndNoListenerIsRegistered" start="39" end="44" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <expectedexception value="\RuntimeException"/>
    </docblock>
  </method>
  <method name="testHandleWhenControllerThrowsAnExceptionAndCatchIsTrueWithAHandlingListener" start="46" end="58" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWhenControllerThrowsAnExceptionAndCatchIsTrueWithANonHandlingListener" start="60" end="77" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleExceptionWithARedirectionResponse" start="79" end="91" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleHttpException" start="93" end="105" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWhenAnExceptionIsHandledWithASpecificStatusCode" start="110" end="122" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <dataprovider value="getStatusCodes"/>
    </docblock>
    <parameter name="responseStatusCode" byreference="false" type="{unknown}"/>
    <parameter name="expectedStatusCode" byreference="false" type="{unknown}"/>
  </method>
  <method name="getStatusCodes" start="124" end="132" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWhenAListenerReturnsAResponse" start="134" end="144" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWhenNoControllerIsFound" start="149" end="155" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <expectedexception value="\Symfony\Component\HttpKernel\Exception\NotFoundHttpException"/>
    </docblock>
  </method>
  <method name="testHandleWhenTheControllerIsNotACallable" start="160" end="166" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <expectedexception value="\LogicException"/>
    </docblock>
  </method>
  <method name="testHandleWhenTheControllerIsAClosure" start="168" end="175" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWhenTheControllerIsAnObjectWithInvoke" start="177" end="183" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWhenTheControllerIsAFunction" start="185" end="191" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWhenTheControllerIsAnArray" start="193" end="199" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWhenTheControllerIsAStaticArray" start="201" end="207" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWhenTheControllerDoesNotReturnAResponse" start="212" end="218" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <expectedexception value="\LogicException"/>
    </docblock>
  </method>
  <method name="testHandleWhenTheControllerDoesNotReturnAResponseButAViewIsRegistered" start="220" end="229" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleWithAResponseListener" start="231" end="240" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testTerminate" start="242" end="258" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testVerifyRequestStackPushPopDuringHandle" start="260" end="272" abstract="false" final="false" static="false" visibility="public"/>
  <method name="getResolver" start="274" end="289" abstract="false" final="false" static="false" visibility="protected">
    <parameter name="controller" byreference="false" type="{unknown}" default="" constant="null"/>
  </method>
  <method name="assertResponseEquals" start="291" end="295" abstract="false" final="false" static="false" visibility="protected">
    <parameter name="expected" byreference="false" type="object">
      <type full="Symfony\Component\HttpFoundation\Response" namespace="Symfony\Component\HttpFoundation" name="Response"/>
    </parameter>
    <parameter name="actual" byreference="false" type="object">
      <type full="Symfony\Component\HttpFoundation\Response" namespace="Symfony\Component\HttpFoundation" name="Response"/>
    </parameter>
  </method>
</class>
