<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Debug\Tests\ExceptionHandlerTest" namespace="Symfony\Component\Debug\Tests" name="ExceptionHandlerTest" abstract="false" final="false" start="21" end="134">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/debug/Tests" file="ExceptionHandlerTest.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/debug/Tests/ExceptionHandlerTest.php" size="4103" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="9e1ad66e2855531ebc0a09ce117f9dd6db17fc85" relative="vendor/symfony/debug/Tests/ExceptionHandlerTest.php"/>
  <extends full="PHPUnit_Framework_TestCase" namespace="" name="PHPUnit_Framework_TestCase"/>
  <method name="setUp" start="23" end="26" abstract="false" final="false" static="false" visibility="protected"/>
  <method name="tearDown" start="28" end="31" abstract="false" final="false" static="false" visibility="protected"/>
  <method name="testDebug" start="33" end="52" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testStatusCode" start="54" end="70" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHeaders" start="72" end="87" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testNestedExceptions" start="89" end="97" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandle" start="99" end="116" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHandleOutOfMemoryException" start="118" end="133" abstract="false" final="false" static="false" visibility="public"/>
</class>
